### ISSUE TITLE
Create process to allow editors to update the confidence level of documents

### ISSUE THREAD

**Issue by markovial** [StampyAI/alignment-research-dataset#134] opened 2023-08-14 18:49 UTC
I dont know if this counts as a duplicate of [this](https://github.com/StampyAI/alignment-research-dataset/issues/107) issue. If so i'll just close it and we can continue using the other one for the overall confidence level thing.

**Comment by ccstan99** [comment] 2023-08-25 06:02
Closing this as duplicate of #107. Changed title of that one to make it more clear.

**Closed by ccstan99** 2023-08-25 06:02 UTC
